--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.435.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 02. 02. 12:54:20
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';



--
USE remekmuvekbeta;


--
INSERT INTO varosok VALUES
(1, 'Ravenna'),
(2, 'Isztambul'),
(3, 'Moszkva'),
(4, 'Hildesheim'),
(5, 'Firenze'),
(6, 'Pisa'),
(7, 'Pannonhalma'),
(8, 'Ják'),
(9, 'Esztergom'),
(10, 'Párizs'),
(11, 'Milánó'),
(12, 'Amiens'),
(13, 'Velence'),
(14, 'Vajdahunyad'),
(15, 'Róma'),
(16, 'Visegrád'),
(17, 'Autun'),
(18, 'Kalocsa'),
(19, 'Székesfehérvár'),
(20, 'Budapest'),
(21, 'Naumburg'),
(22, 'Barcelona'),
(23, 'Krakkó'),
(24, 'Kassa'),
(25, 'Nincsen adat!');

-- 
-- Dumping data for table stilusok
--
INSERT INTO stilusok VALUES
(1, 'Gótikus'),
(2, 'Román'),
(3, 'Nincsen adat!');

-- 
-- Dumping data for table orszagok
--
INSERT INTO orszagok VALUES
(1, 'Olaszország'),
(2, 'Németország'),
(3, 'Oroszország'),
(4, 'Magyarország'),
(5, 'Franciaország'),
(6, 'Spanyolország'),
(7, 'Egyesült Királyság'),
(8, 'Lenygelország'),
(9, 'Nincsen adat!');

-- 
-- Dumping data for table kategoriak
--
INSERT INTO kategoriak VALUES
(1, 'Építészet'),
(2, 'Szobrászat'),
(3, 'Festészet'),
(4, 'Nincsen adat!');

-- 
-- Dumping data for table remekmuvek
--
-- Table remekmuvekdb.remekmuvek does not contain any data (it is empty)

-- 
-- Dumping data for table felhasznalok
--
INSERT INTO felhasznalok VALUES
(1, 'Dobrosi Gergő', 'gergo', '$2y$10$zLWRdlqhzTs65TCINxnfW.CqNTmG6Av2Npu4dZrLByCqBOKVlcJRG', 'asd@asd.com', 'Szerkesztő');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;